POST localhost:8080/api/auth/sign-up
Content-Type: application/json

{
  "username": "qwe",
  "password": "qwe123",
  "firstName": "John",
  "lastName": "Smith",
  "workplace": "SURGERY__TREATMENT_ROOM"
}

###

GET localhost:8080/login
Content-Type: application/x-www-form-urlencoded

username=qwe&password=qwe123
#{
#  "username": "qwe",
#  "password": "qwe123"
#}

###

GET localhost:8080/logout

###

POST localhost:8080/api/auth/login
Content-Type: application/x-www-form-urlencoded

username=qwe&password=qwe123
#email=asd&password=asd123
#username=qwe&password=qwe123

###

GET localhost:8080/api/users/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJxd2UiLCJleHAiOjE2OTczMjU2MzMsIndvcmtwbGFjZSI6IlNVUkdFUllfX1RSRUFUTUVOVF9ST09NIiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL2FwaS9hdXRoL2xvZ2luIn0.LVprmgerWBL_kg_JuwM2ESaroBtdF_ON5mwpljx2XRU
#Authorization: Bearer 9301712e-8de3-44d3-a78d-cf1a1e365e1f

###

POST localhost:8080/auth/token
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJxd2UiLCJleHAiOjE2OTczMTIzMDksInJvbGUiOiJBRE1JTiIsImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6ODA4MC9hdXRoL3Rva2VuIn0.MjNoge88Kfws1M8Gf2EsVdsPaDbKaPTWAwNXK0npwoY

# если accessToken выдаёт ошибку 401, то веб-приложение должно отправлять refreshToken