POST {{myHost}}/api/auth/register
Content-Type: application/x-www-form-urlencoded

username=qwe&password=qwe123&name=Svetlana Schmidt&workplace=SURGERY__TREATMENT_ROOM&position=Krankenschwester

###

GET {{myHost}}/api/auth/login
Content-Type: application/x-www-form-urlencoded

username=qwe&password=qwe123


###

GET {{myHost}}/api/auth/logout
